resources:
- name: repo
  type: git
  source:
    uri: https://github.com/kurtmc/test-cloudformation-resource.git
    branch: master

- name: my-stack
  type: cloudformation
  source:
    name: my-stack
    aws_access_key_id: {{aws-admin-access-key-id}}
    aws_secret_access_key: {{aws-admin-secret-access-key}}
    region: ap-southeast-2

jobs:
- name: deploy-stack
  plan:
    - get: repo
      trigger: true
    - put: my-stack
      params:
        template: repo/bucket.json
